### ISSUE TITLE
Support for composite types

### ISSUE THREAD

**Issue by meticoeus** [kristiandupont/kanel#123]
Would love to see support for composite types. e.g.

```sql
CREATE TYPE inventory_item AS (
    name            text,
    supplier_id     integer,
    price           numeric
);
```

From a quick look at the source, looks like this would require adding support in extract-pg-schema first.

I may be able to spend time working on a PR for this for both projects if there is any interest.

Maybe this could be added as compositeTypes: [] in the extractSchema return value to prevent breaking changes?

**Comment by kristiandupont** [comment]
Yes, that needs to go into extract-pg-schema. I don't (currently) use any composite types myself which is why it's not (currently) supported. But this would be a nice addition. At the moment, extract-pg-schema creates a `types` property which could include these as well (they in turn have a `type` property which could say `'composite'`). 

It's not the easiest library to extend but if you are up for it, you are very welcome to give it a shot. Otherwise I will probably get around to it at some point, but it could easily be half a year or so.

**Comment by meticoeus** [comment]
I've completed a PR for [extract-pg-schema#95](https://github.com/kristiandupont/extract-pg-schema/pull/95). and I've started working on adding support to kanel.

Reviewing the propertyNominator signature, I see a couple different options for how to proceed.

Option A:

Incorporate `CompositeType` into `Model` and keep just 1 property nominator (breaking TS change and breaking JS change `isView` -> `type`):

```ts
type TableModel = TableOrView & {
  type: 'table'
}

type ViewModel = TableOrView & {
  type: 'view'
}

type CompositeTypeModel = CompositeType & {
  type: 'composite'
}

type Model = TableModel | ViewModel | CompositeTypeModel
```

Option B:

Leave Model as-is and add a separate nominator just for composite types:

```ts
export type Nominators = {
  ...
  /** Customize Composite Type properties. */
  attributeNominator: (propertyName: string, model: CompositeType) => string;
  ...
}
```

This would result in fewer changes for people using nominators to make but seems messier.

For quick reference, the type difference between `TableOrView` and `CompositeType` is that `Column` is a strict superset of `Attribute` with several more properties so I've typed `CompositeType` with `attributes: Attribute[]` for an unambiguous difference and so that the type check difference occurs with the parent instead of needing a type or boolean property in `Column` to determine if those extra properties apply.

If you have any other ideas for approaching this, let me know.

**Comment by kristiandupont** [comment]
This is an interesting problem (and, curiously, related to a [blog post](https://kristiandupont.medium.com/and-naming-things-tailwind-css-typescript-and-mammals-9eab459633d2) that I just wrote).

Something to include in the considerations is that I am planning to improve the treatment of views. Currently, information about foreign keys are lost which means that id's are stored as numbers/strings/whatever, instead of the branded types. I am not happy with that.
