### ISSUE TITLE
Specify different customTypeMap for read and write

### ISSUE THREAD

**Issue by LarsJK** [kristiandupont/kanel#140]
Is it possible to specify different types for reading and writing in customTypeMap?

When I read a timestamp field it always returns a string, but when I write to it it should allow both Date and string.

**Comment by kristiandupont** [comment]
Interesting. So would you like two interfaces for each model XxxRead and XxxWrite?

I have been thinking that it could make sense to have an "updater" (if anyone can think of a better word, please let me know! "Mutator"?) interface alongside the initializer. After all, there might be some differences between the three.

**Comment by LarsJK** [comment]
Yeah i think a seperate interface for updates would make sense, and I think Naming it Updater is fine. 

So you would have:
Model, ModelUpdater and ModelInitializer

**Comment by meticoeus** [comment]
I suggest adding an optional customWriteTypeMap to further customize the typing for the initializer and updater models. I think having it default to the customTypeMap would make sense to keep config to a minimum. Example:

```ts
const defaultWriteMap = {
  timestampz: 'Date | string',
  // other special cases go here
}

const writeTypeMap = {
  // sensible defaults
  ...defaultWriteMap,
  // fallback to customTypeMap if provided
  ...(config.customTypeMap || {}),
  // use the new config object if provided
  ...(config.customWriteTypeMap || {}),
)
```

If the defaults cover most or even all of the cases like dates, then hopefully this wouldn't normally need to be configured, just used internally.

Relevant type mapping will affect #82 since function parameters will need to handle the appropriate allowed input types from JS to PSQL.

**Comment by kristiandupont** [comment]
This should finally be addressed :-)

There is a premajor version out that supports creating initializers and mutators. You can specify quite detailed what you want them to look like. There are significant breaking changes though, and the API is not final so feel free to experiment if you like. The documentation is work in progress still, you can start here:
https://github.com/kristiandupont/kanel/blob/v3/docs/configuring.md
