### ISSUE TITLE
Differences with @rmp135/sql-ts

### ISSUE THREAD

**Issue by jgonera** [kristiandupont/kanel#175]
Hi,

It seems `kanel` is very similar to `@rmp135/sql-ts` which seems to be over 2 years older. What was the motivation for creating `kanel` / what are the key differences?

**Comment by kristiandupont** [comment]
That's a fair question. The truth is that I didn't see this library when I started. I knew of Schemats which seems to be the most popular solution and that didn't (at the time) support some of the features that I needed. I believe it was enums and nominal types for identifiers.

Another part of the answer is that this library is only part of a bigger system that I use in Submotion. The other part adds typesafe querying on top of Knex (and yes, there are a bunch of alternatives to that as well) and a system for automatically synchronizing data from backend to frontend. I add metadata with tags in the comments. I've been asked to open the source for this many times and I promise that I am planning to do it, but it only really became possible recently with https://github.com/microsoft/TypeScript/issues/13995 closed and it is still a bit of un-entanglement work so I am not going to give a release date.

So.

`sql-ts` looks like a nice and fully-featured library so I think you will be fine choosing either. Note that there are numerous others as well! There was a discussion recently on Hacker News that mentions many: https://news.ycombinator.com/item?id=27570058

It looks like `sql-ts` allows you more flexibility with the output because of the handlebar templates (which is a good idea -- I might steal it some day! :-)). 

On the other hand, it appears to only generate one type per table. Kanel generates specific initializer types as well which might or might not be relevant for you. It also does not appear to generate nominal types for identifiers which is something that I would not like to live without.

**Comment by jgonera** [comment]
Thank you for a quick and detailed answer! There are so many solutions listed in that Hacker News thread. I kinda wish there were fewer but more mature ones :) I tried pgtyped and zapatos already and hit some problems with them so now I'm looking for something simpler.

Regarding initializer types, I think that's what `sql-ts` actually generates. From the first look it seems like you can get a non-initializer type by simply doing `Required<TypeName>` since the difference between what you need for `INSERT` vs. `SELECT` is just which properties are optional (unless I'm missing something, which I probably am).

What do you use nominal types for IDs for? Is it somehow important for the querying part you built on top of Knex?

**Comment by kristiandupont** [comment]
Good point.

I like to have nominally typed id's because column names don't always imply their reference. For instance, I have two entities related to people: `member` and `account`. In another table, I have a column called `owner`, which refers to a member. Since that now has the type `MemberId` rather than just a string (which is the type underneath), I protect myself from accidentally providing an account id in some query, which would be very bad.
