### ISSUE TITLE
Custom column type output

### ISSUE THREAD

**Issue by Kim-Andersen** [kristiandupont/kanel#273]
Hi. First of all, great project. It has the exact scope and simplicity that I'm looking for.

I have one question/feature request though:
I would like to use `kanal` with [kysely](https://github.com/koskimas/kysely) and as you can see in the [kysely example](https://github.com/koskimas/kysely#minimal-example), the following syntax is used for auto-generated columns like ids and dates (so they are automatically made optional in inserts and updates).

```ts
import { Generated} from 'kysely';
...
interface PersonTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;
  ...
}
```

So, is is possible with kanel to format the property type, so I can do something like the following?:
Pseudo code:
```js
propertyTypeNominator: (...) => {
  if id ...bla bla bla... return `Generated<number>`;
}
```

Thanks in advance.

**Comment by kristiandupont** [comment]
Thank you for the kind words!

And, you are asking at a fortunate time. I am doing a major rewrite, both of [extract-pg-schema](github.com/kristiandupont/extract-pg-schema/) and Kanel, so I will include this in my considerations. Two things I want to add is support for the Knex [knex/types/tables](https://knexjs.org/guide/#typescript) module and [Zod](https://github.com/colinhacks/zod) schemas.

Now, I have had the approach that Kanel is opinionated, mostly because it was just a script extracted from my work and grew from there. But it does seem like it could benefit from a more flexible pipeline that allows you to write generators for custom things. The only thing I need to balance is to what extend it makes sense versus simply writing another package that takes the output from extract-pg-schema and does something.

**Comment by Kim-Andersen** [comment]
Sounds great. Looking forward to that.

Meanwhile, in case this is of interest to someone else, I managed to convert the `kanel` output to be `kysely`-friendly:

```ts
import { Generated } from 'kysely';
import { ModelTypeMap } from '../shared/db-models';

/**
 * Sets `Generated` type for `id` and `created_at` properties so they work correctly with kysely's type system.
 * 
 * https://github.com/koskimas/kysely#minimal-example
 */
type WithKyselyGeneratedType<T extends object> = {
  [K in keyof T]: K extends 'id'  ? Generated<number> 
    : K extends 'created_at' ? Generated<Date>
    : T[K];
};

type Kyselyfy<T extends {[key: string]: any}> = {
  [K in keyof T]: WithKyselyGeneratedType<T[K]>
};

export type Database = Kyselyfy<ModelTypeMap>;
```

**Comment by kristiandupont** [comment]
So just in case you are still interested a year later, I just published a scruffy first version of [kanel-kysely](https://www.npmjs.com/package/kanel-kysely). Feedback is highly appreciated!

**Comment by Kim-Andersen** [comment]
Great. I will check it out asap, currently on vacation.

**Comment by rodrigomf24** [comment]
> So just in case you are still interested a year later, I just published a scruffy first version of [kanel-kysely](https://www.npmjs.com/package/kanel-kysely). Feedback is highly appreciated!

@kristiandupont  do you know if it is possible to exclude tables?

**Comment by kristiandupont** [comment]
@rodrigomf24 yes, that is possible with the [typeFilte](https://kristiandupont.github.io/kanel/configuring.html#typefilter) configuration property. I should improve the documentation but basically it takes a predicate:

```js
const config = {
  // ...
  typeFilter: (t) => !['something-excluded', 'another-excluded-item'].includes(t.name)
}
```

The input parameter (`t`) is a [PgType](https://kristiandupont.github.io/extract-pg-schema/api/extract-pg-schema.pgtype.html)
