### ISSUE TITLE
add propertyHooks

### ISSUE THREAD

**Issue by janmeier** [kristiandupont/kanel#83]
Right now I'm using `modelHooks` to replace the types of some of the generated columns. For example, providing more specific types for JSON columns.

Right now I have to loop through all lines and find the ones matching the properties, to replace the type. I'm thinking this could be more smooth if kanel provided an option to override the types on a per property basis - We could call it `propertyHooks` 

WDYT?

**Comment by kristiandupont** [comment]
Yeah I can see why that solution is annoying! There is actually an undocumented feature that might help you. If you create a comment on your column, you can specify a custom type like this:
```sql
COMMENT ON COLUMN user.details IS 'This JSON object contains additional user details @type:UserDetails';
```

I don't know if that is feasible in your particular situation. Otherwise, something like your suggestion might be the way to go, I just need to think about all the potential scenarios..

**Comment by janmeier** [comment]
What about when the `UserDetails` type is defined in another file - How is it imported into the model file?

**Comment by kristiandupont** [comment]
@janmeier there is a corresponding `externalTypesFolder` property per schema in the kanelrc file that you can set for that. So right now, all "external" types are expected to reside in that same folder. I am not sure that will be the way to go forward but it works for me at the moment.

**Comment by janmeier** [comment]
Ah, that was the part I was missing - Thanks :)
