### ISSUE TITLE
Which postgres node adapter complements this generator?

### ISSUE THREAD

**Issue by olso** [kristiandupont/kanel#9]
Hi, I've found your project via HN comment section

We've been using https://www.npmjs.com/package/schemats + https://sqorn.org/docs/about.html

But both projects are stagnant now 😔

Basically I'm looking for `somePgNodeAdapter` in this example, to complement your project

```ts
// GeneratedDb.Account is provided by kanel

const account = await somePgNodeAdapter<GeneratedDb.Account>
    .from(tables.accountTable)
    .insert({
      // These would get checked against GeneratedDb.Account
      firebaseUid,
      firstName: input.firstName,
      lastName: input.lastName,
      langCode: "en",
      email: input.email,
      createdAt: nowTimestamptzSq(),
      updatedAt: nowTimestamptzSq(),
    })
    .return("id") // These would also be checked against GeneratedDb.Account
    .one()
```

Are you using something like this?

**Comment by olso** [comment]
Since we can generate safe typescript types from pg schema, there is no reason duplicate this in some ORM model definitions... like all the ORM's force us to do

**Comment by kristiandupont** [comment]
I am. I've written a wrapper around [knex](http://knexjs.org/) that does this for me. It's still entangled in the project where I extracted this module from so it's not open source yet but it is my plan to extract it as well.

Knex has some degree of type safety that I use as well, so that might be a nice place to start.
